// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT9ueRFmd8CsFtb6VyRkjwLuVNy1sDsHM',
    appId: '1:896423596342:web:95a76103ace72aa40ae397',
    messagingSenderId: '896423596342',
    projectId: 'stocks-global',
    authDomain: 'stocks-global.firebaseapp.com',
    storageBucket: 'stocks-global.firebasestorage.app',
    measurementId: 'G-4JSGJ99VWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAeUN_CjHJGdLNiU1DU9vrc9h3qGnfp3U',
    appId: '1:896423596342:android:199c05f9590f4e630ae397',
    messagingSenderId: '896423596342',
    projectId: 'stocks-global',
    storageBucket: 'stocks-global.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5GeTEH70pEuNFbISFS2tS8QvVqC7u5Gs',
    appId: '1:896423596342:ios:ccef7845f531fbab0ae397',
    messagingSenderId: '896423596342',
    projectId: 'stocks-global',
    storageBucket: 'stocks-global.firebasestorage.app',
    iosClientId: '896423596342-00mej18v31ibt15gpie3jhcanribu80i.apps.googleusercontent.com',
    iosBundleId: 'com.example.sotcks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5GeTEH70pEuNFbISFS2tS8QvVqC7u5Gs',
    appId: '1:896423596342:ios:ccef7845f531fbab0ae397',
    messagingSenderId: '896423596342',
    projectId: 'stocks-global',
    storageBucket: 'stocks-global.firebasestorage.app',
    iosClientId: '896423596342-00mej18v31ibt15gpie3jhcanribu80i.apps.googleusercontent.com',
    iosBundleId: 'com.example.sotcks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT9ueRFmd8CsFtb6VyRkjwLuVNy1sDsHM',
    appId: '1:896423596342:web:90053032938f49400ae397',
    messagingSenderId: '896423596342',
    projectId: 'stocks-global',
    authDomain: 'stocks-global.firebaseapp.com',
    storageBucket: 'stocks-global.firebasestorage.app',
    measurementId: 'G-VRK1C3W26T',
  );
}
