// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHWm3Dtv_wYjGfC-mWLcRcTJ1lNJPMVBA',
    appId: '1:961714047293:web:32c30e83ae47d5e7305d54',
    messagingSenderId: '961714047293',
    projectId: 'velix-socialize',
    authDomain: 'velix-socialize.firebaseapp.com',
    storageBucket: 'velix-socialize.firebasestorage.app',
    measurementId: 'G-MMT65HTZBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdwKs-y8aPM26f0j6ORXbX5SjKf3AIF28',
    appId: '1:961714047293:android:409ffed620e2da9b305d54',
    messagingSenderId: '961714047293',
    projectId: 'velix-socialize',
    storageBucket: 'velix-socialize.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4ICBW7NpBV8BMaXYSZKiIQtL1MGozDQw',
    appId: '1:961714047293:ios:b696a368a1400b28305d54',
    messagingSenderId: '961714047293',
    projectId: 'velix-socialize',
    storageBucket: 'velix-socialize.firebasestorage.app',
    iosClientId: '961714047293-fpvpia1lfbv11jd3c24omdt9m8te53it.apps.googleusercontent.com',
    iosBundleId: 'com.example.velix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4ICBW7NpBV8BMaXYSZKiIQtL1MGozDQw',
    appId: '1:961714047293:ios:b696a368a1400b28305d54',
    messagingSenderId: '961714047293',
    projectId: 'velix-socialize',
    storageBucket: 'velix-socialize.firebasestorage.app',
    iosClientId: '961714047293-fpvpia1lfbv11jd3c24omdt9m8te53it.apps.googleusercontent.com',
    iosBundleId: 'com.example.velix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHWm3Dtv_wYjGfC-mWLcRcTJ1lNJPMVBA',
    appId: '1:961714047293:web:626678e593a3d0ff305d54',
    messagingSenderId: '961714047293',
    projectId: 'velix-socialize',
    authDomain: 'velix-socialize.firebaseapp.com',
    storageBucket: 'velix-socialize.firebasestorage.app',
    measurementId: 'G-7CH619EHYX',
  );
}
