USE linguapath;
INSERT INTO vocabulary (word, part_of_speech, cefr_level, category, example, exam_tags) VALUES
('ask','verb','A1','communication','Can I ask you a question?','TOEIC'),
('buy','verb','A1','shopping','I want to buy a new phone.','TOEIC'),
('come','verb','A1','movement','Please come here.',''),
('find','verb','A1','general','I cannot find my keys.',''),
('give','verb','A1','communication','Can you give me a hand?','TOEIC'),
('know','verb','A1','general','Do you know the answer?',''),
('like','verb','A1','emotion','I like music.',''),
('look','verb','A1','senses','Look at the sky.',''),
('make','verb','A1','general','She can make great food.',''),
('need','verb','A1','general','I need some help.','TOEIC'),
('see','verb','A1','senses','I can see the ocean.',''),
('take','verb','A1','general','Take your time.','TOEIC'),
('think','verb','A1','general','I think he is right.',''),
('use','verb','A1','general','How do you use this tool?',''),
('want','verb','A1','emotion','She wants to be a doctor.',''),
('work','verb','A1','profession','I work at a hospital.','TOEIC'),
('write','verb','A1','communication','Please write your name here.',''),
('big','adjective','A1','description','That is a big house.',''),
('good','adjective','A1','description','She is a good student.',''),
('happy','adjective','A1','emotion','The children are happy.',''),
('new','adjective','A1','description','I got a new bag.',''),
('old','adjective','A1','description','This building is very old.',''),
('small','adjective','A1','description','She lives in a small room.',''),
('young','adjective','A1','description','He is a young doctor.',''),
('today','adverb','A1','time','The meeting is today.','TOEIC'),
('always','adverb','A2','frequency','She always arrives on time.','TOEIC'),
('sometimes','adverb','A2','frequency','I sometimes cook at home.',''),
('never','adverb','A2','frequency','He never forgets a name.',''),
('usually','adverb','A2','frequency','We usually eat dinner together.',''),
('often','adverb','A2','frequency','She often reads before bed.',''),
('already','adverb','A2','time','I have already finished.','TOEIC'),
('together','adverb','A2','manner','Let us work together.',''),
('agree','verb','B1','communication','I agree with your idea.','TOEIC'),
('allow','verb','B1','permission','The rule does not allow that.','TOEIC'),
('apply','verb','B1','action','You should apply for the job.','TOEIC'),
('avoid','verb','B1','action','Try to avoid mistakes.','TOEIC,TOEFL'),
('believe','verb','B1','general','I believe in your ability.',''),
('cause','verb','B1','general','What caused the problem?','TOEFL'),
('change','verb','B1','action','Things change over time.','TOEFL'),
('choose','verb','B1','decision','Choose the best answer.','TOEFL'),
('consider','verb','B1','thinking','Please consider my suggestion.','TOEIC,TOEFL'),
('continue','verb','B1','action','Please continue your work.','TOEIC'),
('create','verb','B1','action','She wants to create new things.','TOEFL'),
('decide','verb','B1','decision','He needs to decide soon.','TOEIC'),
('describe','verb','B1','communication','Can you describe the problem?','TOEFL'),
('discuss','verb','B1','communication','Let us discuss the plan.','TOEIC,TOEFL'),
('explain','verb','B1','communication','Please explain the rules.','TOEIC,TOEFL'),
('follow','verb','B1','action','Follow the instructions.','TOEIC'),
('happen','verb','B1','general','What happened yesterday?',''),
('hope','verb','B1','emotion','I hope you feel better.',''),
('improve','verb','B1','action','Reading helps improve your vocabulary.','TOEIC,TOEFL'),
('include','verb','B1','general','The price includes tax.','TOEIC,TOEFL'),
('increase','verb','B1','change','Sales have increased this month.','TOEIC,TOEFL'),
('inform','verb','B1','communication','Please inform us of any changes.','TOEIC'),
('involve','verb','B1','general','This project involves many teams.','TOEFL'),
('join','verb','B1','social','Would you like to join us?','TOEIC'),
('keep','verb','B1','action','Keep the receipt for records.','TOEIC'),
('learn','verb','B1','education','She loves to learn new things.',''),
('manage','verb','B1','business','He manages a team of ten.','TOEIC'),
('mention','verb','B1','communication','She mentioned a new project.','TOEIC'),
('move','verb','B1','action','We are planning to move offices.','TOEIC'),
('notice','verb','B1','perception','Did you notice anything different?','TOEFL'),
('offer','verb','B1','business','They offered a better price.','TOEIC'),
('organize','verb','B1','business','She organized the whole event.','TOEIC,TOEFL'),
('plan','verb','B1','planning','We need to plan carefully.','TOEIC'),
('prepare','verb','B1','action','Prepare your documents in advance.','TOEIC'),
('produce','verb','B1','business','The factory produces 500 units daily.','TOEIC,TOEFL'),
('reach','verb','B1','action','We reached an agreement.','TOEIC'),
('receive','verb','B1','communication','I received your email today.','TOEIC'),
('reduce','verb','B1','change','We must reduce costs.','TOEIC,TOEFL'),
('remember','verb','B1','mental','Remember to submit the form.',''),
('report','verb','B1','business','Please report any issues immediately.','TOEIC'),
('request','verb','B1','communication','I would like to request a refund.','TOEIC'),
('return','verb','B1','action','He returned the book to the library.','TOEIC'),
('review','verb','B1','business','Please review the document.','TOEIC'),
('send','verb','B1','communication','I will send the file tomorrow.','TOEIC'),
('share','verb','B1','social','She shared her ideas with the team.','TOEIC'),
('solve','verb','B1','thinking','We need to solve this problem.','TOEFL'),
('start','verb','B1','action','The meeting starts at nine.','TOEIC'),
('suggest','verb','B1','communication','May I suggest a different approach?','TOEIC,TOEFL'),
('support','verb','B1','action','We support your decision.','TOEIC,TOEFL'),
('understand','verb','B1','mental','Do you understand the instructions?','TOEFL'),
('visit','verb','B1','travel','We plan to visit the new branch.','TOEIC'),
('able','adjective','B1','description','She is able to handle pressure.','TOEFL'),
('available','adjective','B1','business','Is the room available tomorrow?','TOEIC'),
('busy','adjective','B1','description','He is too busy to answer calls.','TOEIC'),
('careful','adjective','B1','description','Be careful with the equipment.',''),
('clear','adjective','B1','description','The instructions are very clear.','TOEIC,TOEFL'),
('current','adjective','B1','time','What is the current status?','TOEIC,TOEFL'),
('different','adjective','B1','description','This approach is different.','TOEFL'),
('difficult','adjective','B1','description','The exam was very difficult.',''),
('direct','adjective','B1','description','Please take the direct route.','TOEIC'),
('effective','adjective','B1','business','This is a very effective method.','TOEIC,TOEFL'),
('free','adjective','B1','description','Admission is free today.','TOEIC'),
('important','adjective','B1','description','This is an important meeting.','TOEIC,TOEFL'),
('local','adjective','B1','place','Support your local community.','TOEIC'),
('necessary','adjective','B1','description','It is necessary to sign here.','TOEIC,TOEFL'),
('possible','adjective','B1','description','Is it possible to reschedule?','TOEIC'),
('recent','adjective','B1','time','Have you seen the recent report?','TOEIC,TOEFL'),
('responsible','adjective','B1','character','Each team member is responsible.','TOEIC'),
('several','adjective','B1','quantity','There are several options.','TOEFL'),
('similar','adjective','B1','comparison','The two products are similar.','TOEFL'),
('specific','adjective','B1','description','Please give a specific example.','TOEIC,TOEFL'),
('successful','adjective','B1','achievement','The campaign was successful.','TOEIC,TOEFL'),
('certain','adjective','B2','description','I am certain of the result.','TOEFL'),
('complex','adjective','B2','description','The system is quite complex.','TOEFL'),
('consistent','adjective','B2','description','Her performance has been consistent.','TOEIC,TOEFL'),
('critical','adjective','B2','description','Time management is critical.','TOEFL'),
('efficient','adjective','B2','business','We need a more efficient process.','TOEIC,TOEFL'),
('flexible','adjective','B2','description','The schedule is flexible.','TOEIC'),
('formal','adjective','B2','description','Please wear formal attire.','TOEIC'),
('global','adjective','B2','world','We operate on a global scale.','TOEIC,TOEFL'),
('initial','adjective','B2','time','The initial results are promising.','TOEIC,TOEFL'),
('obvious','adjective','B2','description','The mistake was obvious.','TOEFL'),
('overall','adjective','B2','description','The overall performance was good.','TOEIC,TOEFL'),
('potential','adjective','B2','description','She has great potential.','TOEIC,TOEFL'),
('precise','adjective','B2','description','Please be precise in your report.','TOEFL'),
('relevant','adjective','B2','description','Only relevant information please.','TOEFL'),
('significant','adjective','B2','description','There has been significant progress.','TOEIC,TOEFL'),
('strategic','adjective','B2','business','We need a strategic plan.','TOEIC'),
('accurate','adjective','C1','description','The data must be accurate.','TOEFL'),
('comprehensive','adjective','C1','description','The report was comprehensive.','TOEFL'),
('controversial','adjective','C1','society','That is a controversial topic.','TOEFL'),
('decisive','adjective','C1','character','A good leader must be decisive.','TOEFL'),
('fundamental','adjective','C1','description','This is a fundamental concept.','TOEFL'),
('inevitable','adjective','C1','description','Change is inevitable.','TOEFL'),
('innovative','adjective','C1','business','The company has an innovative approach.','TOEFL'),
('sophisticated','adjective','C1','description','The system is highly sophisticated.','TOEFL'),
('sustainable','adjective','C1','environment','We need sustainable solutions.','TOEFL'),
('transparent','adjective','C1','description','The process must be transparent.','TOEIC,TOEFL'),
('versatile','adjective','C1','description','She is a versatile professional.','TOEFL'),
('agenda','noun','B1','business','What is on the agenda for today?','TOEIC'),
('approach','noun','B1','general','We need a new approach.','TOEFL'),
('argument','noun','B1','academic','His argument was very convincing.','TOEFL'),
('attitude','noun','B1','character','Her attitude towards work is positive.','TOEFL'),
('benefit','noun','B1','general','Exercise has many benefits.','TOEIC,TOEFL'),
('budget','noun','B1','finance','We need to cut the budget.','TOEIC'),
('category','noun','B1','classification','Sort items into categories.','TOEFL'),
('challenge','noun','B1','general','Every challenge is an opportunity.','TOEFL'),
('colleague','noun','B1','profession','She introduced me to her colleagues.','TOEIC'),
('concern','noun','B1','emotion','She raised a valid concern.','TOEIC'),
('conclusion','noun','B1','academic','The conclusion was well-argued.','TOEFL'),
('conference','noun','B1','business','She attended an international conference.','TOEIC'),
('contract','noun','B1','business','Sign the contract by Friday.','TOEIC'),
('data','noun','B1','academic','The data supports our hypothesis.','TOEIC,TOEFL'),
('deadline','noun','B1','business','The deadline is next Monday.','TOEIC'),
('decision','noun','B1','general','This is an important decision.','TOEIC'),
('definition','noun','B1','academic','Give a clear definition.','TOEFL'),
('demand','noun','B1','business','Demand for the product is high.','TOEIC'),
('department','noun','B1','business','Which department do you work in?','TOEIC'),
('detail','noun','B1','description','Please include more detail.','TOEIC,TOEFL'),
('development','noun','B1','general','The development of AI is fast.','TOEFL'),
('discussion','noun','B1','communication','The discussion lasted two hours.','TOEIC'),
('document','noun','B1','business','Please check the document.','TOEIC'),
('education','noun','B1','academic','Education is a human right.','TOEFL'),
('effect','noun','B1','general','What is the effect of this change?','TOEFL'),
('effort','noun','B1','action','Thank you for your effort.','TOEIC'),
('environment','noun','B1','nature','Protect the environment.','TOEFL'),
('experience','noun','B1','general','She has five years of experience.','TOEIC'),
('expert','noun','B1','profession','Consult an expert before deciding.','TOEIC'),
('feedback','noun','B1','communication','Your feedback is valuable.','TOEIC'),
('focus','noun','B1','general','The focus of the meeting is safety.','TOEIC,TOEFL'),
('goal','noun','B1','general','Set a clear goal and work toward it.','TOEIC,TOEFL'),
('growth','noun','B1','change','The company saw steady growth.','TOEIC,TOEFL'),
('guideline','noun','B1','instruction','Follow the company guidelines.','TOEIC'),
('instruction','noun','B1','communication','Follow the instructions carefully.','TOEIC'),
('issue','noun','B1','general','We have a technical issue.','TOEIC'),
('management','noun','B1','business','She studied management in college.','TOEIC'),
('method','noun','B1','academic','Which method works best?','TOEFL'),
('opportunity','noun','B1','general','This is a great opportunity.','TOEIC'),
('overview','noun','B1','description','Give an overview of the project.','TOEIC'),
('performance','noun','B1','business','Monitor performance regularly.','TOEIC'),
('procedure','noun','B1','instruction','Follow the standard procedure.','TOEIC'),
('process','noun','B1','general','The process takes three days.','TOEIC,TOEFL'),
('profit','noun','B1','finance','The company made a large profit.','TOEIC'),
('project','noun','B1','work','The project ends in December.','TOEIC'),
('purpose','noun','B1','general','What is the purpose of this form?','TOEIC,TOEFL'),
('requirement','noun','B1','general','What are the requirements?','TOEIC,TOEFL'),
('research','noun','B1','academic','She is doing research on climate.','TOEFL'),
('resource','noun','B1','general','Manage your resources wisely.','TOEIC,TOEFL'),
('responsibility','noun','B1','work','It is your responsibility.','TOEIC'),
('result','noun','B1','general','The test results were positive.','TOEIC,TOEFL'),
('risk','noun','B1','general','There is always some risk involved.','TOEIC'),
('schedule','noun','B1','time','What is on the schedule today?','TOEIC'),
('skill','noun','B1','education','Communication is an important skill.','TOEIC'),
('solution','noun','B1','problem-solving','We need a practical solution.','TOEIC,TOEFL'),
('source','noun','B1','academic','Cite your sources.','TOEFL'),
('task','noun','B1','work','Complete all tasks by end of day.','TOEIC'),
('technology','noun','B1','science','Technology changes quickly.','TOEFL'),
('timeline','noun','B1','planning','Give me a project timeline.','TOEIC'),
('value','noun','B1','general','What are your core values?','TOEIC'),
('analysis','noun','B2','academic','A thorough analysis is required.','TOEIC,TOEFL'),
('aspect','noun','B2','general','Consider every aspect of the plan.','TOEFL'),
('assumption','noun','B2','thinking','Do not make assumptions.','TOEFL'),
('authority','noun','B2','society','Who has the authority to approve?','TOEFL'),
('commitment','noun','B2','character','His commitment to quality is clear.','TOEIC,TOEFL'),
('competition','noun','B2','business','The competition is fierce.','TOEIC'),
('concept','noun','B2','academic','Explain the concept clearly.','TOEFL'),
('conflict','noun','B2','society','We must resolve the conflict.','TOEFL'),
('consequence','noun','B2','general','Think about the consequences.','TOEFL'),
('contribution','noun','B2','general','Her contribution was recognized.','TOEIC,TOEFL'),
('debate','noun','B2','academic','There is ongoing debate on this topic.','TOEFL'),
('diversity','noun','B2','society','Diversity strengthens teams.','TOEFL'),
('economy','noun','B2','society','The economy is recovering.','TOEFL'),
('efficiency','noun','B2','business','We need to improve efficiency.','TOEIC,TOEFL'),
('evidence','noun','B2','academic','Show me the evidence.','TOEFL'),
('factor','noun','B2','academic','Cost is a key factor.','TOEFL'),
('finance','noun','B2','business','She works in finance.','TOEIC'),
('impact','noun','B2','general','Technology has a huge impact on life.','TOEIC,TOEFL'),
('implementation','noun','B2','business','Implementation begins next month.','TOEIC,TOEFL'),
('initiative','noun','B2','business','She launched a new initiative.','TOEIC,TOEFL'),
('innovation','noun','B2','business','Innovation drives the economy.','TOEIC,TOEFL'),
('investment','noun','B2','finance','This is a wise investment.','TOEIC,TOEFL'),
('leadership','noun','B2','management','Good leadership is essential.','TOEIC,TOEFL'),
('limitation','noun','B2','general','Every approach has its limitations.','TOEFL'),
('majority','noun','B2','quantity','The majority agreed.','TOEFL'),
('outcome','noun','B2','general','The outcome was better than expected.','TOEFL'),
('pattern','noun','B2','academic','The data shows a clear pattern.','TOEFL'),
('perspective','noun','B2','thinking','Consider other perspectives.','TOEFL'),
('policy','noun','B2','society','The company policy must be followed.','TOEIC,TOEFL'),
('priority','noun','B2','general','What is your top priority?','TOEIC'),
('proposal','noun','B2','business','Submit your proposal by Friday.','TOEIC'),
('qualification','noun','B2','education','List your qualifications.','TOEIC'),
('revenue','noun','B2','finance','Revenue grew by twenty percent.','TOEIC'),
('standard','noun','B2','description','We maintain high standards.','TOEIC'),
('statistics','noun','B2','academic','The statistics are surprising.','TOEFL'),
('strategy','noun','B2','business','We need a new marketing strategy.','TOEIC,TOEFL'),
('structure','noun','B2','academic','The structure of the report is clear.','TOEFL'),
('trend','noun','B2','general','Follow the latest business trends.','TOEIC,TOEFL'),
('barrier','noun','B2','general','Language can be a barrier.','TOEFL'),
('accountability','noun','C1','business','Accountability is key in leadership.','TOEFL'),
('emphasis','noun','C1','academic','The emphasis was on quality.','TOEFL'),
('hypothesis','noun','C1','academic','Test your hypothesis carefully.','TOEFL'),
('ideology','noun','C1','society','The ideology shaped the movement.','TOEFL'),
('implication','noun','C1','academic','Consider the implications.','TOEFL'),
('integrity','noun','C1','character','Integrity is non-negotiable.','TOEFL'),
('phenomenon','noun','C1','academic','This is a rare phenomenon.','TOEFL'),
('principle','noun','B2','general','Act on strong principles.','TOEFL'),
('insight','noun','C1','thinking','Her insight was very helpful.','TOEFL');
