import type { ComponentType, ComponentDefinition } from '@circuit-lab/shared';

export const COMPONENT_LIBRARY: Record<ComponentType, ComponentDefinition> = {
  resistor: {
    type: 'resistor',
    name: 'Resistor',
    category: 'passive',
    description: 'Resists current flow, converting electrical energy to heat',
    ports: [
      { id: 'p1', name: 'Pin 1', position: { x: -0.5, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'p2', name: 'Pin 2', position: { x: 0.5, y: 0, z: 0 }, type: 'bidirectional' },
    ],
    defaultProperties: { resistance: 1000, tolerance: 5, power: 0.25 },
    size: { width: 1, height: 0.3, depth: 0.3 },
    spiceModel: 'R {name} {p1} {p2} {resistance}',
  },
  capacitor: {
    type: 'capacitor',
    name: 'Capacitor',
    category: 'passive',
    description: 'Stores electrical energy in an electric field',
    ports: [
      { id: 'p1', name: 'Pin 1', position: { x: -0.5, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'p2', name: 'Pin 2', position: { x: 0.5, y: 0, z: 0 }, type: 'bidirectional' },
    ],
    defaultProperties: { capacitance: 1e-6, voltage: 16 },
    size: { width: 0.8, height: 0.4, depth: 0.4 },
    spiceModel: 'C {name} {p1} {p2} {capacitance}',
  },
  inductor: {
    type: 'inductor',
    name: 'Inductor',
    category: 'passive',
    description: 'Stores electrical energy in a magnetic field',
    ports: [
      { id: 'p1', name: 'Pin 1', position: { x: -0.5, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'p2', name: 'Pin 2', position: { x: 0.5, y: 0, z: 0 }, type: 'bidirectional' },
    ],
    defaultProperties: { inductance: 1e-3, current: 1 },
    size: { width: 0.8, height: 0.4, depth: 0.4 },
    spiceModel: 'L {name} {p1} {p2} {inductance}',
  },
  diode: {
    type: 'diode',
    name: 'Diode',
    category: 'active',
    description: 'Allows current flow in one direction only',
    ports: [
      { id: 'anode', name: 'Anode', position: { x: -0.4, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'cathode', name: 'Cathode', position: { x: 0.4, y: 0, z: 0 }, type: 'bidirectional' },
    ],
    defaultProperties: { saturationCurrent: 1e-12, emissionCoeff: 1 },
    size: { width: 0.6, height: 0.3, depth: 0.3 },
    spiceModel: 'D {name} {anode} {cathode} D1N4148',
  },
  led: {
    type: 'led',
    name: 'LED',
    category: 'active',
    description: 'Light-emitting diode',
    ports: [
      { id: 'anode', name: 'Anode (+)', position: { x: -0.4, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'cathode', name: 'Cathode (-)', position: { x: 0.4, y: 0, z: 0 }, type: 'bidirectional' },
    ],
    defaultProperties: { forwardVoltage: 2.0, current: 0.02, color: 'red' },
    size: { width: 0.5, height: 0.5, depth: 0.5 },
    spiceModel: 'D {name} {anode} {cathode} LED_{color}',
  },
  zener_diode: {
    type: 'zener_diode',
    name: 'Zener Diode',
    category: 'active',
    description: 'Diode that conducts in reverse at a specified breakdown voltage',
    ports: [
      { id: 'anode', name: 'Anode', position: { x: -0.4, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'cathode', name: 'Cathode', position: { x: 0.4, y: 0, z: 0 }, type: 'bidirectional' },
    ],
    defaultProperties: { zenerVoltage: 5.1, saturationCurrent: 1e-12 },
    size: { width: 0.6, height: 0.3, depth: 0.3 },
    spiceModel: 'D {name} {anode} {cathode} D1N750',
  },
  npn_transistor: {
    type: 'npn_transistor',
    name: 'NPN Transistor',
    category: 'active',
    description: 'NPN bipolar junction transistor for amplification and switching',
    ports: [
      { id: 'base', name: 'Base (B)', position: { x: 0, y: 0.4, z: 0 }, type: 'bidirectional' },
      { id: 'collector', name: 'Collector (C)', position: { x: -0.3, y: -0.3, z: 0 }, type: 'bidirectional' },
      { id: 'emitter', name: 'Emitter (E)', position: { x: 0.3, y: -0.3, z: 0 }, type: 'bidirectional' },
    ],
    defaultProperties: { beta: 100, vbe: 0.7 },
    size: { width: 0.5, height: 0.7, depth: 0.3 },
    spiceModel: 'Q {name} {collector} {base} {emitter} NPN_MODEL',
  },
  pnp_transistor: {
    type: 'pnp_transistor',
    name: 'PNP Transistor',
    category: 'active',
    description: 'PNP bipolar junction transistor',
    ports: [
      { id: 'base', name: 'Base (B)', position: { x: 0, y: 0.4, z: 0 }, type: 'bidirectional' },
      { id: 'collector', name: 'Collector (C)', position: { x: -0.3, y: -0.3, z: 0 }, type: 'bidirectional' },
      { id: 'emitter', name: 'Emitter (E)', position: { x: 0.3, y: -0.3, z: 0 }, type: 'bidirectional' },
    ],
    defaultProperties: { beta: 100, vbe: 0.7 },
    size: { width: 0.5, height: 0.7, depth: 0.3 },
    spiceModel: 'Q {name} {collector} {base} {emitter} PNP_MODEL',
  },
  mosfet_n: {
    type: 'mosfet_n',
    name: 'N-Channel MOSFET',
    category: 'active',
    description: 'N-channel metal-oxide-semiconductor field-effect transistor',
    ports: [
      { id: 'gate', name: 'Gate (G)', position: { x: 0, y: 0.4, z: 0 }, type: 'bidirectional' },
      { id: 'drain', name: 'Drain (D)', position: { x: -0.3, y: -0.3, z: 0 }, type: 'bidirectional' },
      { id: 'source', name: 'Source (S)', position: { x: 0.3, y: -0.3, z: 0 }, type: 'bidirectional' },
    ],
    defaultProperties: { vth: 2.0, k: 0.1 },
    size: { width: 0.5, height: 0.7, depth: 0.3 },
    spiceModel: 'M {name} {drain} {gate} {source} {source} NMOS_MODEL',
  },
  mosfet_p: {
    type: 'mosfet_p',
    name: 'P-Channel MOSFET',
    category: 'active',
    description: 'P-channel MOSFET',
    ports: [
      { id: 'gate', name: 'Gate (G)', position: { x: 0, y: 0.4, z: 0 }, type: 'bidirectional' },
      { id: 'drain', name: 'Drain (D)', position: { x: -0.3, y: -0.3, z: 0 }, type: 'bidirectional' },
      { id: 'source', name: 'Source (S)', position: { x: 0.3, y: -0.3, z: 0 }, type: 'bidirectional' },
    ],
    defaultProperties: { vth: -2.0, k: 0.1 },
    size: { width: 0.5, height: 0.7, depth: 0.3 },
    spiceModel: 'M {name} {drain} {gate} {source} {source} PMOS_MODEL',
  },
  op_amp: {
    type: 'op_amp',
    name: 'Op-Amp',
    category: 'active',
    description: 'Operational amplifier',
    ports: [
      { id: 'n_inv', name: 'Inverting (-)', position: { x: -0.5, y: 0.2, z: 0 }, type: 'input' },
      { id: 'n_noninv', name: 'Non-inverting (+)', position: { x: -0.5, y: -0.2, z: 0 }, type: 'input' },
      { id: 'v_out', name: 'Output', position: { x: 0.5, y: 0, z: 0 }, type: 'output' },
      { id: 'v_pos', name: 'V+', position: { x: 0, y: 0.5, z: 0 }, type: 'power' },
      { id: 'v_neg', name: 'V-', position: { x: 0, y: -0.5, z: 0 }, type: 'power' },
    ],
    defaultProperties: { gain: 100000, slewRate: 0.5 },
    size: { width: 1, height: 1, depth: 0.4 },
  },
  '555_timer': {
    type: '555_timer',
    name: '555 Timer',
    category: 'active',
    description: 'Versatile timer IC for astable and monostable operation',
    ports: [
      { id: 'gnd', name: 'GND (1)', position: { x: -0.5, y: -0.5, z: 0 }, type: 'power' },
      { id: 'trig', name: 'TRIG (2)', position: { x: -0.5, y: 0.5, z: 0 }, type: 'input' },
      { id: 'out', name: 'OUT (3)', position: { x: 0.5, y: 0.5, z: 0 }, type: 'output' },
      { id: 'reset', name: 'RESET (4)', position: { x: 0.5, y: -0.5, z: 0 }, type: 'input' },
      { id: 'ctrl', name: 'CTRL (5)', position: { x: 0, y: -0.7, z: 0 }, type: 'input' },
      { id: 'thresh', name: 'THRES (6)', position: { x: 0, y: 0.7, z: 0 }, type: 'input' },
      { id: 'disch', name: 'DISCH (7)', position: { x: -0.5, y: 0, z: 0.5 }, type: 'output' },
      { id: 'vcc', name: 'VCC (8)', position: { x: 0.5, y: 0, z: 0.5 }, type: 'power' },
    ],
    defaultProperties: { vcc: 5.0 },
    size: { width: 1, height: 1.4, depth: 0.6 },
  },
  battery: {
    type: 'battery',
    name: 'Battery',
    category: 'power',
    description: 'DC voltage source',
    ports: [
      { id: 'positive', name: 'Positive (+)', position: { x: 0, y: 0.3, z: 0 }, type: 'power' },
      { id: 'negative', name: 'Negative (-)', position: { x: 0, y: -0.3, z: 0 }, type: 'power' },
    ],
    defaultProperties: { voltage: 9.0 },
    size: { width: 0.8, height: 0.6, depth: 0.5 },
    spiceModel: 'V {name} {positive} {negative} {voltage}',
  },
  voltage_source: {
    type: 'voltage_source',
    name: 'Voltage Source',
    category: 'power',
    description: 'Ideal DC voltage source',
    ports: [
      { id: 'positive', name: 'Positive (+)', position: { x: 0, y: 0.3, z: 0 }, type: 'power' },
      { id: 'negative', name: 'Negative (-)', position: { x: 0, y: -0.3, z: 0 }, type: 'power' },
    ],
    defaultProperties: { voltage: 5.0, acMagnitude: 0, acPhase: 0 },
    size: { width: 0.7, height: 0.7, depth: 0.4 },
    spiceModel: 'V {name} {positive} {negative} DC {voltage}',
  },
  current_source: {
    type: 'current_source',
    name: 'Current Source',
    category: 'power',
    description: 'Ideal DC current source',
    ports: [
      { id: 'positive', name: 'Positive (+)', position: { x: 0, y: 0.3, z: 0 }, type: 'power' },
      { id: 'negative', name: 'Negative (-)', position: { x: 0, y: -0.3, z: 0 }, type: 'power' },
    ],
    defaultProperties: { current: 0.01 },
    size: { width: 0.7, height: 0.7, depth: 0.4 },
    spiceModel: 'I {name} {positive} {negative} DC {current}',
  },
  potentiometer: {
    type: 'potentiometer',
    name: 'Potentiometer',
    category: 'passive',
    description: 'Variable resistor with three terminals',
    ports: [
      { id: 'p1', name: 'Pin 1', position: { x: -0.5, y: 0.3, z: 0 }, type: 'bidirectional' },
      { id: 'wiper', name: 'Wiper', position: { x: 0.5, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'p2', name: 'Pin 2', position: { x: -0.5, y: -0.3, z: 0 }, type: 'bidirectional' },
    ],
    defaultProperties: { maxResistance: 10000, wiperPosition: 0.5 },
    size: { width: 1, height: 0.6, depth: 0.4 },
    spiceModel: 'R {name}_1 {p1} {wiper} {R1}\nR {name}_2 {wiper} {p2} {R2}',
  },
  switch_spst: {
    type: 'switch_spst',
    name: 'SPST Switch',
    category: 'electromechanical',
    description: 'Single-pole single-throw switch',
    ports: [
      { id: 'p1', name: 'Pin 1', position: { x: -0.4, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'p2', name: 'Pin 2', position: { x: 0.4, y: 0, z: 0 }, type: 'bidirectional' },
    ],
    defaultProperties: { closed: false },
    size: { width: 0.8, height: 0.3, depth: 0.2 },
  },
  push_button: {
    type: 'push_button',
    name: 'Push Button',
    category: 'electromechanical',
    description: 'Momentary tactile switch',
    ports: [
      { id: 'p1', name: 'Pin 1', position: { x: -0.3, y: 0.3, z: 0 }, type: 'bidirectional' },
      { id: 'p2', name: 'Pin 2', position: { x: 0.3, y: 0.3, z: 0 }, type: 'bidirectional' },
      { id: 'p3', name: 'Pin 3', position: { x: -0.3, y: -0.3, z: 0 }, type: 'bidirectional' },
      { id: 'p4', name: 'Pin 4', position: { x: 0.3, y: -0.3, z: 0 }, type: 'bidirectional' },
    ],
    defaultProperties: { pressed: false },
    size: { width: 0.6, height: 0.6, depth: 0.4 },
  },
  buzzer: {
    type: 'buzzer',
    name: 'Buzzer',
    category: 'electromechanical',
    description: 'Piezo buzzer for sound output',
    ports: [
      { id: 'positive', name: 'Positive (+)', position: { x: -0.4, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'negative', name: 'Negative (-)', position: { x: 0.4, y: 0, z: 0 }, type: 'bidirectional' },
    ],
    defaultProperties: { frequency: 1000, voltage: 5 },
    size: { width: 0.8, height: 0.5, depth: 0.5 },
  },
  dc_motor: {
    type: 'dc_motor',
    name: 'DC Motor',
    category: 'electromechanical',
    description: 'DC motor',
    ports: [
      { id: 'p1', name: 'Terminal 1', position: { x: -0.4, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'p2', name: 'Terminal 2', position: { x: 0.4, y: 0, z: 0 }, type: 'bidirectional' },
    ],
    defaultProperties: { voltage: 5, loadTorque: 0 },
    size: { width: 0.8, height: 0.8, depth: 0.8 },
  },
  seven_segment: {
    type: 'seven_segment',
    name: '7-Segment Display',
    category: 'display',
    description: 'Seven-segment LED display',
    ports: [
      { id: 'a', name: 'Segment A', position: { x: -0.5, y: 0.4, z: 0 }, type: 'input' },
      { id: 'b', name: 'Segment B', position: { x: 0, y: 0.6, z: 0 }, type: 'input' },
      { id: 'c', name: 'Segment C', position: { x: 0.5, y: 0.4, z: 0 }, type: 'input' },
      { id: 'd', name: 'Segment D', position: { x: 0.5, y: -0.4, z: 0 }, type: 'input' },
      { id: 'e', name: 'Segment E', position: { x: 0, y: -0.6, z: 0 }, type: 'input' },
      { id: 'f', name: 'Segment F', position: { x: -0.5, y: -0.4, z: 0 }, type: 'input' },
      { id: 'g', name: 'Segment G', position: { x: 0, y: 0, z: 0.5 }, type: 'input' },
      { id: 'dp', name: 'Decimal Point', position: { x: 0.5, y: 0, z: 0.5 }, type: 'input' },
      { id: 'com', name: 'Common', position: { x: -0.5, y: 0, z: 0.5 }, type: 'power' },
    ],
    defaultProperties: { commonType: 'cathode' },
    size: { width: 1, height: 1.2, depth: 0.3 },
  },
  arduino_mega2560: {
    type: 'arduino_mega2560',
    name: 'Arduino Mega 2560',
    category: 'microcontroller',
    description: 'ATmega2560-based board with 54 digital I/O pins, 16 analog inputs',
    ports: [
      { id: 'vcc', name: '5V', position: { x: 0, y: 1.2, z: 0 }, type: 'power' },
      { id: 'gnd', name: 'GND', position: { x: 0, y: -1.2, z: 0 }, type: 'power' },
      { id: '3v3', name: '3.3V', position: { x: -0.8, y: 1.2, z: 0 }, type: 'power' },
      { id: 'vin', name: 'Vin', position: { x: 0.8, y: 1.2, z: 0 }, type: 'power' },
      { id: 'd0', name: 'D0/RX', position: { x: -0.7, y: 1.0, z: 0 }, type: 'bidirectional' },
      { id: 'd1', name: 'D1/TX', position: { x: -0.7, y: 0.8, z: 0 }, type: 'bidirectional' },
      { id: 'd2', name: 'D2', position: { x: -0.7, y: 0.6, z: 0 }, type: 'bidirectional' },
      { id: 'd3', name: 'D3 (PWM)', position: { x: -0.7, y: 0.4, z: 0 }, type: 'bidirectional' },
      { id: 'd4', name: 'D4', position: { x: -0.7, y: 0.2, z: 0 }, type: 'bidirectional' },
      { id: 'd5', name: 'D5 (PWM)', position: { x: -0.7, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'd6', name: 'D6 (PWM)', position: { x: -0.7, y: -0.2, z: 0 }, type: 'bidirectional' },
      { id: 'd7', name: 'D7', position: { x: -0.7, y: -0.4, z: 0 }, type: 'bidirectional' },
      { id: 'd8', name: 'D8', position: { x: -0.7, y: -0.6, z: 0 }, type: 'bidirectional' },
      { id: 'd9', name: 'D9 (PWM)', position: { x: -0.7, y: -0.8, z: 0 }, type: 'bidirectional' },
      { id: 'd10', name: 'D10 (PWM)', position: { x: -0.7, y: -1.0, z: 0 }, type: 'bidirectional' },
      { id: 'd11', name: 'D11 (PWM)', position: { x: 0.7, y: -1.0, z: 0 }, type: 'bidirectional' },
      { id: 'd12', name: 'D12', position: { x: 0.7, y: -0.8, z: 0 }, type: 'bidirectional' },
      { id: 'd13', name: 'D13', position: { x: 0.7, y: -0.6, z: 0 }, type: 'bidirectional' },
      { id: 'd14', name: 'D14', position: { x: 0.7, y: -0.4, z: 0 }, type: 'bidirectional' },
      { id: 'd15', name: 'D15', position: { x: 0.7, y: -0.2, z: 0 }, type: 'bidirectional' },
      { id: 'd16', name: 'D16', position: { x: 0.7, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'd17', name: 'D17', position: { x: 0.7, y: 0.2, z: 0 }, type: 'bidirectional' },
      { id: 'd18', name: 'D18', position: { x: 0.7, y: 0.4, z: 0 }, type: 'bidirectional' },
      { id: 'd19', name: 'D19', position: { x: 0.7, y: 0.6, z: 0 }, type: 'bidirectional' },
      { id: 'd20', name: 'D20 (SDA)', position: { x: 0.7, y: 0.8, z: 0 }, type: 'bidirectional' },
      { id: 'd21', name: 'D21 (SCL)', position: { x: 0.7, y: 1.0, z: 0 }, type: 'bidirectional' },
      { id: 'a0', name: 'A0', position: { x: 0.3, y: 1.0, z: 0.5 }, type: 'bidirectional' },
      { id: 'a1', name: 'A1', position: { x: 0.3, y: 0.8, z: 0.5 }, type: 'bidirectional' },
      { id: 'a2', name: 'A2', position: { x: 0.3, y: 0.6, z: 0.5 }, type: 'bidirectional' },
      { id: 'a3', name: 'A3', position: { x: 0.3, y: 0.4, z: 0.5 }, type: 'bidirectional' },
      { id: 'a4', name: 'A4', position: { x: 0.3, y: 0.2, z: 0.5 }, type: 'bidirectional' },
      { id: 'a5', name: 'A5', position: { x: 0.3, y: 0, z: 0.5 }, type: 'bidirectional' },
      { id: 'a6', name: 'A6', position: { x: 0.3, y: -0.2, z: 0.5 }, type: 'bidirectional' },
      { id: 'a7', name: 'A7', position: { x: 0.3, y: -0.4, z: 0.5 }, type: 'bidirectional' },
      { id: 'a8', name: 'A8', position: { x: 0.3, y: -0.6, z: 0.5 }, type: 'bidirectional' },
      { id: 'a9', name: 'A9', position: { x: 0.3, y: -0.8, z: 0.5 }, type: 'bidirectional' },
      { id: 'a10', name: 'A10', position: { x: 0.3, y: -1.0, z: 0.5 }, type: 'bidirectional' },
      { id: 'a11', name: 'A11', position: { x: 0.3, y: -1.2, z: 0.5 }, type: 'bidirectional' },
      { id: 'a12', name: 'A12', position: { x: -0.3, y: -1.2, z: 0.5 }, type: 'bidirectional' },
      { id: 'a13', name: 'A13', position: { x: -0.3, y: -1.0, z: 0.5 }, type: 'bidirectional' },
      { id: 'a14', name: 'A14', position: { x: -0.3, y: -0.8, z: 0.5 }, type: 'bidirectional' },
      { id: 'a15', name: 'A15', position: { x: -0.3, y: -0.6, z: 0.5 }, type: 'bidirectional' },
      { id: 'reset', name: 'RESET', position: { x: -0.3, y: 1.2, z: 0.5 }, type: 'input' },
    ],
    defaultProperties: { clockSpeed: 16000000, operatingVoltage: 5, flashKB: 256, sramKB: 8 },
    size: { width: 2.0, height: 2.4, depth: 0.3 },
  },
  arduino_uno: {
    type: 'arduino_uno',
    name: 'Arduino Uno R3',
    category: 'microcontroller',
    description: 'ATmega328P-based Arduino Uno Rev3 board',
    ports: [
      { id: 'vcc', name: '5V', position: { x: 0, y: 0.8, z: 0 }, type: 'power' },
      { id: 'gnd', name: 'GND', position: { x: 0, y: -0.8, z: 0 }, type: 'power' },
      { id: 'd0', name: 'D0/RX', position: { x: -0.5, y: 0.6, z: 0 }, type: 'bidirectional' },
      { id: 'd1', name: 'D1/TX', position: { x: -0.5, y: 0.4, z: 0 }, type: 'bidirectional' },
      { id: 'd2', name: 'D2', position: { x: -0.5, y: 0.2, z: 0 }, type: 'bidirectional' },
      { id: 'd3', name: 'D3 (PWM)', position: { x: -0.5, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'd4', name: 'D4', position: { x: -0.5, y: -0.2, z: 0 }, type: 'bidirectional' },
      { id: 'd5', name: 'D5 (PWM)', position: { x: -0.5, y: -0.4, z: 0 }, type: 'bidirectional' },
      { id: 'd6', name: 'D6 (PWM)', position: { x: -0.5, y: -0.6, z: 0 }, type: 'bidirectional' },
      { id: 'd7', name: 'D7', position: { x: -0.5, y: -0.8, z: 0 }, type: 'bidirectional' },
      { id: 'd8', name: 'D8', position: { x: 0.5, y: -0.8, z: 0 }, type: 'bidirectional' },
      { id: 'd9', name: 'D9 (PWM)', position: { x: 0.5, y: -0.6, z: 0 }, type: 'bidirectional' },
      { id: 'd10', name: 'D10 (PWM)', position: { x: 0.5, y: -0.4, z: 0 }, type: 'bidirectional' },
      { id: 'd11', name: 'D11 (PWM)', position: { x: 0.5, y: -0.2, z: 0 }, type: 'bidirectional' },
      { id: 'd12', name: 'D12', position: { x: 0.5, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'd13', name: 'D13 (LED)', position: { x: 0.5, y: 0.2, z: 0 }, type: 'bidirectional' },
      { id: 'a0', name: 'A0', position: { x: 0.5, y: 0.4, z: 0 }, type: 'bidirectional' },
      { id: 'a1', name: 'A1', position: { x: 0.5, y: 0.6, z: 0 }, type: 'bidirectional' },
      { id: 'a2', name: 'A2', position: { x: 0.5, y: 0.8, z: 0 }, type: 'bidirectional' },
      { id: 'a3', name: 'A3', position: { x: 0.7, y: 0.6, z: 0 }, type: 'bidirectional' },
      { id: 'a4', name: 'A4 (SDA)', position: { x: 0.7, y: 0.4, z: 0 }, type: 'bidirectional' },
      { id: 'a5', name: 'A5 (SCL)', position: { x: 0.7, y: 0.2, z: 0 }, type: 'bidirectional' },
      { id: 'vin', name: 'Vin', position: { x: 0.7, y: 0, z: 0 }, type: 'power' },
      { id: '3v3', name: '3.3V', position: { x: 0.7, y: -0.2, z: 0 }, type: 'power' },
      { id: 'reset', name: 'RESET', position: { x: 0.7, y: -0.4, z: 0 }, type: 'input' },
    ],
    defaultProperties: { clockSpeed: 16000000, operatingVoltage: 5 },
    size: { width: 1.5, height: 1.6, depth: 0.3 },
  },
  esp32: {
    type: 'esp32',
    name: 'ESP32',
    category: 'microcontroller',
    description: 'ESP32 WiFi/Bluetooth microcontroller',
    ports: [
      { id: 'vcc', name: '3.3V', position: { x: 0, y: 0.6, z: 0 }, type: 'power' },
      { id: 'gnd', name: 'GND', position: { x: 0, y: -0.6, z: 0 }, type: 'power' },
      { id: 'd0', name: 'GPIO0', position: { x: -0.5, y: 0.4, z: 0 }, type: 'bidirectional' },
      { id: 'd1', name: 'GPIO1/TX', position: { x: -0.5, y: 0.2, z: 0 }, type: 'bidirectional' },
      { id: 'd2', name: 'GPIO2', position: { x: -0.5, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'd3', name: 'GPIO3/RX', position: { x: -0.5, y: -0.2, z: 0 }, type: 'bidirectional' },
      { id: 'd4', name: 'GPIO4', position: { x: -0.5, y: -0.4, z: 0 }, type: 'bidirectional' },
      { id: 'd5', name: 'GPIO5', position: { x: 0.5, y: -0.4, z: 0 }, type: 'bidirectional' },
      { id: 'd12', name: 'GPIO12', position: { x: 0.5, y: -0.2, z: 0 }, type: 'bidirectional' },
      { id: 'd13', name: 'GPIO13', position: { x: 0.5, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'd14', name: 'GPIO14', position: { x: 0.5, y: 0.2, z: 0 }, type: 'bidirectional' },
      { id: 'd15', name: 'GPIO15', position: { x: 0.5, y: 0.4, z: 0 }, type: 'bidirectional' },
      { id: 'en', name: 'EN', position: { x: 0.7, y: 0, z: 0 }, type: 'input' },
    ],
    defaultProperties: { clockSpeed: 240000000, operatingVoltage: 3.3 },
    size: { width: 1.2, height: 1.2, depth: 0.3 },
  },
  esp32_s3: {
    type: 'esp32_s3',
    name: 'ESP32-S3',
    category: 'microcontroller',
    description: 'ESP32-S3 with dual-core Xtensa LX7, USB OTG, AI accelerator',
    ports: [
      { id: 'vcc', name: '3.3V', position: { x: 0, y: 0.6, z: 0 }, type: 'power' },
      { id: 'gnd', name: 'GND', position: { x: 0, y: -0.6, z: 0 }, type: 'power' },
      { id: 'd0', name: 'GPIO0', position: { x: -0.5, y: 0.5, z: 0 }, type: 'bidirectional' },
      { id: 'd1', name: 'GPIO1', position: { x: -0.5, y: 0.3, z: 0 }, type: 'bidirectional' },
      { id: 'd2', name: 'GPIO2', position: { x: -0.5, y: 0.1, z: 0 }, type: 'bidirectional' },
      { id: 'd3', name: 'GPIO3', position: { x: -0.5, y: -0.1, z: 0 }, type: 'bidirectional' },
      { id: 'd4', name: 'GPIO4', position: { x: -0.5, y: -0.3, z: 0 }, type: 'bidirectional' },
      { id: 'd5', name: 'GPIO5', position: { x: -0.5, y: -0.5, z: 0 }, type: 'bidirectional' },
      { id: 'd6', name: 'GPIO6', position: { x: 0.5, y: -0.5, z: 0 }, type: 'bidirectional' },
      { id: 'd7', name: 'GPIO7', position: { x: 0.5, y: -0.3, z: 0 }, type: 'bidirectional' },
      { id: 'd8', name: 'GPIO8', position: { x: 0.5, y: -0.1, z: 0 }, type: 'bidirectional' },
      { id: 'd9', name: 'GPIO9', position: { x: 0.5, y: 0.1, z: 0 }, type: 'bidirectional' },
      { id: 'd10', name: 'GPIO10', position: { x: 0.5, y: 0.3, z: 0 }, type: 'bidirectional' },
      { id: 'd11', name: 'GPIO11', position: { x: 0.5, y: 0.5, z: 0 }, type: 'bidirectional' },
      { id: 'd12', name: 'GPIO12', position: { x: 0.7, y: 0.5, z: 0 }, type: 'bidirectional' },
      { id: 'd13', name: 'GPIO13', position: { x: 0.7, y: 0.3, z: 0 }, type: 'bidirectional' },
      { id: 'd14', name: 'GPIO14', position: { x: 0.7, y: 0.1, z: 0 }, type: 'bidirectional' },
      { id: 'd15', name: 'GPIO15', position: { x: 0.7, y: -0.1, z: 0 }, type: 'bidirectional' },
      { id: 'd16', name: 'GPIO16', position: { x: 0.7, y: -0.3, z: 0 }, type: 'bidirectional' },
      { id: 'd17', name: 'GPIO17', position: { x: 0.7, y: -0.5, z: 0 }, type: 'bidirectional' },
      { id: 'usb_dp', name: 'USB D+', position: { x: -0.7, y: 0.5, z: 0 }, type: 'bidirectional' },
      { id: 'usb_dn', name: 'USB D-', position: { x: -0.7, y: 0.3, z: 0 }, type: 'bidirectional' },
      { id: 'en', name: 'EN', position: { x: -0.7, y: -0.5, z: 0 }, type: 'input' },
    ],
    defaultProperties: { clockSpeed: 240000000, operatingVoltage: 3.3, psramMB: 8, flashMB: 16 },
    size: { width: 1.4, height: 1.2, depth: 0.3 },
  },
  raspberry_pi_pico: {
    type: 'raspberry_pi_pico',
    name: 'Raspberry Pi Pico',
    category: 'microcontroller',
    description: 'RP2040-based Raspberry Pi Pico board',
    ports: [
      { id: 'vbus', name: 'VBUS', position: { x: 0, y: 0.6, z: 0 }, type: 'power' },
      { id: 'vsys', name: 'VSYS', position: { x: 0.4, y: 0.6, z: 0 }, type: 'power' },
      { id: 'gnd', name: 'GND', position: { x: 0, y: -0.6, z: 0 }, type: 'power' },
      { id: 'gp0', name: 'GP0', position: { x: -0.5, y: 0.4, z: 0 }, type: 'bidirectional' },
      { id: 'gp1', name: 'GP1', position: { x: -0.5, y: 0.2, z: 0 }, type: 'bidirectional' },
      { id: 'gp2', name: 'GP2', position: { x: -0.5, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'gp3', name: 'GP3', position: { x: -0.5, y: -0.2, z: 0 }, type: 'bidirectional' },
      { id: 'gp4', name: 'GP4', position: { x: -0.5, y: -0.4, z: 0 }, type: 'bidirectional' },
      { id: 'gp5', name: 'GP5', position: { x: -0.6, y: -0.6, z: 0 }, type: 'bidirectional' },
      { id: 'gp6', name: 'GP6', position: { x: 0.6, y: -0.6, z: 0 }, type: 'bidirectional' },
      { id: 'gp7', name: 'GP7', position: { x: 0.5, y: -0.4, z: 0 }, type: 'bidirectional' },
      { id: 'gp8', name: 'GP8', position: { x: 0.5, y: -0.2, z: 0 }, type: 'bidirectional' },
      { id: 'gp9', name: 'GP9', position: { x: 0.5, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'gp10', name: 'GP10', position: { x: 0.5, y: 0.2, z: 0 }, type: 'bidirectional' },
      { id: 'gp11', name: 'GP11', position: { x: 0.5, y: 0.4, z: 0 }, type: 'bidirectional' },
      { id: 'gp12', name: 'GP12', position: { x: 0.6, y: 0.6, z: 0 }, type: 'bidirectional' },
      { id: 'gp13', name: 'GP13', position: { x: -0.6, y: 0.6, z: 0 }, type: 'bidirectional' },
      { id: 'adc0', name: 'ADC0', position: { x: 0.7, y: 0.2, z: 0 }, type: 'bidirectional' },
      { id: 'adc1', name: 'ADC1', position: { x: 0.7, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'adc2', name: 'ADC2', position: { x: 0.7, y: -0.2, z: 0 }, type: 'bidirectional' },
      { id: 'run', name: 'RUN', position: { x: 0.7, y: -0.4, z: 0 }, type: 'input' },
    ],
    defaultProperties: { clockSpeed: 133000000, operatingVoltage: 3.3 },
    size: { width: 1.2, height: 1.2, depth: 0.3 },
  },
  raspberry_pi_pico_2w: {
    type: 'raspberry_pi_pico_2w',
    name: 'Raspberry Pi Pico 2W',
    category: 'microcontroller',
    description: 'RP2350-based Pico 2W with WiFi/Bluetooth, dual-core Cortex-M33 + RISC-V',
    ports: [
      { id: 'vbus', name: 'VBUS', position: { x: 0, y: 0.6, z: 0 }, type: 'power' },
      { id: 'vsys', name: 'VSYS', position: { x: 0.4, y: 0.6, z: 0 }, type: 'power' },
      { id: 'gnd', name: 'GND', position: { x: 0, y: -0.6, z: 0 }, type: 'power' },
      { id: '3v3', name: '3.3V', position: { x: -0.4, y: 0.6, z: 0 }, type: 'power' },
      { id: 'gp0', name: 'GP0', position: { x: -0.5, y: 0.5, z: 0 }, type: 'bidirectional' },
      { id: 'gp1', name: 'GP1', position: { x: -0.5, y: 0.3, z: 0 }, type: 'bidirectional' },
      { id: 'gp2', name: 'GP2', position: { x: -0.5, y: 0.1, z: 0 }, type: 'bidirectional' },
      { id: 'gp3', name: 'GP3', position: { x: -0.5, y: -0.1, z: 0 }, type: 'bidirectional' },
      { id: 'gp4', name: 'GP4', position: { x: -0.5, y: -0.3, z: 0 }, type: 'bidirectional' },
      { id: 'gp5', name: 'GP5', position: { x: -0.5, y: -0.5, z: 0 }, type: 'bidirectional' },
      { id: 'gp6', name: 'GP6', position: { x: -0.6, y: -0.6, z: 0 }, type: 'bidirectional' },
      { id: 'gp7', name: 'GP7', position: { x: 0.6, y: -0.6, z: 0 }, type: 'bidirectional' },
      { id: 'gp8', name: 'GP8', position: { x: 0.5, y: -0.5, z: 0 }, type: 'bidirectional' },
      { id: 'gp9', name: 'GP9', position: { x: 0.5, y: -0.3, z: 0 }, type: 'bidirectional' },
      { id: 'gp10', name: 'GP10', position: { x: 0.5, y: -0.1, z: 0 }, type: 'bidirectional' },
      { id: 'gp11', name: 'GP11', position: { x: 0.5, y: 0.1, z: 0 }, type: 'bidirectional' },
      { id: 'gp12', name: 'GP12', position: { x: 0.5, y: 0.3, z: 0 }, type: 'bidirectional' },
      { id: 'gp13', name: 'GP13', position: { x: 0.5, y: 0.5, z: 0 }, type: 'bidirectional' },
      { id: 'gp14', name: 'GP14', position: { x: 0.6, y: 0.6, z: 0 }, type: 'bidirectional' },
      { id: 'gp15', name: 'GP15', position: { x: -0.6, y: 0.6, z: 0 }, type: 'bidirectional' },
      { id: 'adc0', name: 'ADC0', position: { x: 0.7, y: 0.3, z: 0 }, type: 'bidirectional' },
      { id: 'adc1', name: 'ADC1', position: { x: 0.7, y: 0.1, z: 0 }, type: 'bidirectional' },
      { id: 'adc2', name: 'ADC2', position: { x: 0.7, y: -0.1, z: 0 }, type: 'bidirectional' },
      { id: 'adc3', name: 'ADC3', position: { x: 0.7, y: -0.3, z: 0 }, type: 'bidirectional' },
      { id: 'run', name: 'RUN', position: { x: 0.7, y: -0.5, z: 0 }, type: 'input' },
      { id: 'wifi_ant', name: 'WiFi Antenna', position: { x: -0.7, y: 0.5, z: 0 }, type: 'bidirectional' },
    ],
    defaultProperties: { clockSpeed: 150000000, operatingVoltage: 3.3, flashMB: 4, sramKB: 520 },
    size: { width: 1.2, height: 1.3, depth: 0.3 },
  },
  raspberry_pi_4: {
    type: 'raspberry_pi_4',
    name: 'Raspberry Pi 4',
    category: 'microcontroller',
    description: 'Raspberry Pi 4 Model B single-board computer',
    ports: [
      { id: '5v', name: '5V', position: { x: 0, y: 0.8, z: 0 }, type: 'power' },
      { id: '3v3', name: '3.3V', position: { x: 0.3, y: 0.8, z: 0 }, type: 'power' },
      { id: 'gnd', name: 'GND', position: { x: 0, y: -0.8, z: 0 }, type: 'power' },
      { id: 'gpio2', name: 'GPIO2 (SDA)', position: { x: -0.5, y: 0.6, z: 0 }, type: 'bidirectional' },
      { id: 'gpio3', name: 'GPIO3 (SCL)', position: { x: -0.5, y: 0.4, z: 0 }, type: 'bidirectional' },
      { id: 'gpio4', name: 'GPIO4', position: { x: -0.5, y: 0.2, z: 0 }, type: 'bidirectional' },
      { id: 'gpio5', name: 'GPIO5', position: { x: -0.5, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'gpio6', name: 'GPIO6', position: { x: -0.5, y: -0.2, z: 0 }, type: 'bidirectional' },
      { id: 'gpio7', name: 'GPIO7', position: { x: -0.5, y: -0.4, z: 0 }, type: 'bidirectional' },
      { id: 'gpio8', name: 'GPIO8', position: { x: -0.5, y: -0.6, z: 0 }, type: 'bidirectional' },
      { id: 'gpio9', name: 'GPIO9', position: { x: -0.5, y: -0.8, z: 0 }, type: 'bidirectional' },
      { id: 'gpio10', name: 'GPIO10', position: { x: 0.5, y: -0.8, z: 0 }, type: 'bidirectional' },
      { id: 'gpio11', name: 'GPIO11', position: { x: 0.5, y: -0.6, z: 0 }, type: 'bidirectional' },
      { id: 'gpio12', name: 'GPIO12', position: { x: 0.5, y: -0.4, z: 0 }, type: 'bidirectional' },
      { id: 'gpio13', name: 'GPIO13', position: { x: 0.5, y: -0.2, z: 0 }, type: 'bidirectional' },
      { id: 'gpio14', name: 'GPIO14 (TXD)', position: { x: 0.5, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'gpio15', name: 'GPIO15 (RXD)', position: { x: 0.5, y: 0.2, z: 0 }, type: 'bidirectional' },
      { id: 'gpio16', name: 'GPIO16', position: { x: 0.5, y: 0.4, z: 0 }, type: 'bidirectional' },
      { id: 'gpio17', name: 'GPIO17', position: { x: 0.5, y: 0.6, z: 0 }, type: 'bidirectional' },
      { id: 'gpio18', name: 'GPIO18', position: { x: 0.5, y: 0.8, z: 0 }, type: 'bidirectional' },
    ],
    defaultProperties: { clockSpeed: 1500000000, operatingVoltage: 3.3, memoryMB: 4096 },
    size: { width: 2.0, height: 1.6, depth: 0.4 },
  },
  raspberry_pi_5: {
    type: 'raspberry_pi_5',
    name: 'Raspberry Pi 5',
    category: 'microcontroller',
    description: 'BCM2712-based Raspberry Pi 5, quad-core Cortex-A76, PCIe 2.0',
    ports: [
      { id: '5v', name: '5V', position: { x: 0, y: 0.8, z: 0 }, type: 'power' },
      { id: '3v3', name: '3.3V', position: { x: 0.3, y: 0.8, z: 0 }, type: 'power' },
      { id: 'gnd', name: 'GND', position: { x: 0, y: -0.8, z: 0 }, type: 'power' },
      { id: 'gpio2', name: 'GPIO2 (SDA)', position: { x: -0.5, y: 0.7, z: 0 }, type: 'bidirectional' },
      { id: 'gpio3', name: 'GPIO3 (SCL)', position: { x: -0.5, y: 0.5, z: 0 }, type: 'bidirectional' },
      { id: 'gpio4', name: 'GPIO4', position: { x: -0.5, y: 0.3, z: 0 }, type: 'bidirectional' },
      { id: 'gpio5', name: 'GPIO5', position: { x: -0.5, y: 0.1, z: 0 }, type: 'bidirectional' },
      { id: 'gpio6', name: 'GPIO6', position: { x: -0.5, y: -0.1, z: 0 }, type: 'bidirectional' },
      { id: 'gpio7', name: 'GPIO7', position: { x: -0.5, y: -0.3, z: 0 }, type: 'bidirectional' },
      { id: 'gpio8', name: 'GPIO8', position: { x: -0.5, y: -0.5, z: 0 }, type: 'bidirectional' },
      { id: 'gpio9', name: 'GPIO9', position: { x: -0.5, y: -0.7, z: 0 }, type: 'bidirectional' },
      { id: 'gpio10', name: 'GPIO10', position: { x: 0.5, y: -0.7, z: 0 }, type: 'bidirectional' },
      { id: 'gpio11', name: 'GPIO11', position: { x: 0.5, y: -0.5, z: 0 }, type: 'bidirectional' },
      { id: 'gpio12', name: 'GPIO12', position: { x: 0.5, y: -0.3, z: 0 }, type: 'bidirectional' },
      { id: 'gpio13', name: 'GPIO13', position: { x: 0.5, y: -0.1, z: 0 }, type: 'bidirectional' },
      { id: 'gpio14', name: 'GPIO14 (TXD)', position: { x: 0.5, y: 0.1, z: 0 }, type: 'bidirectional' },
      { id: 'gpio15', name: 'GPIO15 (RXD)', position: { x: 0.5, y: 0.3, z: 0 }, type: 'bidirectional' },
      { id: 'gpio16', name: 'GPIO16', position: { x: 0.5, y: 0.5, z: 0 }, type: 'bidirectional' },
      { id: 'gpio17', name: 'GPIO17', position: { x: 0.5, y: 0.7, z: 0 }, type: 'bidirectional' },
      { id: 'gpio18', name: 'GPIO18', position: { x: 0.5, y: 0.9, z: 0 }, type: 'bidirectional' },
      { id: 'gpio19', name: 'GPIO19', position: { x: 0.5, y: 1.1, z: 0 }, type: 'bidirectional' },
      { id: 'gpio20', name: 'GPIO20', position: { x: -0.5, y: 1.1, z: 0 }, type: 'bidirectional' },
      { id: 'gpio21', name: 'GPIO21', position: { x: -0.5, y: 0.9, z: 0 }, type: 'bidirectional' },
      { id: 'pci_clk', name: 'PCIe CLK', position: { x: 0.7, y: 0.7, z: 0 }, type: 'bidirectional' },
      { id: 'pci_txp', name: 'PCIe TX+', position: { x: 0.7, y: 0.5, z: 0 }, type: 'bidirectional' },
      { id: 'pci_txn', name: 'PCIe TX-', position: { x: 0.7, y: 0.3, z: 0 }, type: 'bidirectional' },
      { id: 'pci_rxp', name: 'PCIe RX+', position: { x: 0.7, y: 0.1, z: 0 }, type: 'bidirectional' },
      { id: 'pci_rxn', name: 'PCIe RX-', position: { x: 0.7, y: -0.1, z: 0 }, type: 'bidirectional' },
    ],
    defaultProperties: { clockSpeed: 2400000000, operatingVoltage: 3.3, memoryMB: 8192, cores: 4 },
    size: { width: 2.2, height: 1.8, depth: 0.4 },
  },
  and_gate: {
    type: 'and_gate',
    name: 'AND Gate',
    category: 'logic',
    description: 'Logical AND gate',
    ports: [
      { id: 'a', name: 'Input A', position: { x: -0.4, y: 0.2, z: 0 }, type: 'input' },
      { id: 'b', name: 'Input B', position: { x: -0.4, y: -0.2, z: 0 }, type: 'input' },
      { id: 'y', name: 'Output Y', position: { x: 0.4, y: 0, z: 0 }, type: 'output' },
      { id: 'vcc', name: 'VCC', position: { x: 0, y: 0.4, z: 0 }, type: 'power' },
      { id: 'gnd', name: 'GND', position: { x: 0, y: -0.4, z: 0 }, type: 'power' },
    ],
    defaultProperties: { family: 'HC', propagationDelay: 10e-9 },
    size: { width: 0.8, height: 0.8, depth: 0.3 },
  },
  or_gate: {
    type: 'or_gate',
    name: 'OR Gate',
    category: 'logic',
    description: 'Logical OR gate',
    ports: [
      { id: 'a', name: 'Input A', position: { x: -0.4, y: 0.2, z: 0 }, type: 'input' },
      { id: 'b', name: 'Input B', position: { x: -0.4, y: -0.2, z: 0 }, type: 'input' },
      { id: 'y', name: 'Output Y', position: { x: 0.4, y: 0, z: 0 }, type: 'output' },
    ],
    defaultProperties: { family: 'HC', propagationDelay: 10e-9 },
    size: { width: 0.8, height: 0.8, depth: 0.3 },
  },
  nand_gate: {
    type: 'nand_gate',
    name: 'NAND Gate',
    category: 'logic',
    description: 'NAND gate - universal logic gate',
    ports: [
      { id: 'a', name: 'Input A', position: { x: -0.4, y: 0.2, z: 0 }, type: 'input' },
      { id: 'b', name: 'Input B', position: { x: -0.4, y: -0.2, z: 0 }, type: 'input' },
      { id: 'y', name: 'Output Y', position: { x: 0.4, y: 0, z: 0 }, type: 'output' },
    ],
    defaultProperties: { family: 'HC', propagationDelay: 10e-9 },
    size: { width: 0.8, height: 0.8, depth: 0.3 },
  },
  vcc: {
    type: 'vcc',
    name: 'VCC',
    category: 'power',
    description: 'Positive power rail terminal',
    ports: [
      { id: 'vcc', name: 'VCC', position: { x: 0, y: 0, z: 0 }, type: 'power' },
    ],
    defaultProperties: { voltage: 5 },
    size: { width: 0.2, height: 0.2, depth: 0.2 },
  },
  gnd: {
    type: 'gnd',
    name: 'GND',
    category: 'power',
    description: 'Ground terminal (0V reference)',
    ports: [
      { id: 'gnd', name: 'GND', position: { x: 0, y: 0, z: 0 }, type: 'power' },
    ],
    defaultProperties: {},
    size: { width: 0.2, height: 0.2, depth: 0.2 },
  },
  not_gate: {
    type: 'not_gate',
    name: 'NOT Gate',
    category: 'logic',
    description: 'Inverter - outputs the complement of input',
    ports: [
      { id: 'a', name: 'Input A', position: { x: -0.4, y: 0, z: 0 }, type: 'input' },
      { id: 'y', name: 'Output Y', position: { x: 0.4, y: 0, z: 0 }, type: 'output' },
    ],
    defaultProperties: { family: 'HC', propagationDelay: 8e-9 },
    size: { width: 0.8, height: 0.5, depth: 0.3 },
  },
  nor_gate: {
    type: 'nor_gate',
    name: 'NOR Gate',
    category: 'logic',
    description: 'Logical NOR gate',
    ports: [
      { id: 'a', name: 'Input A', position: { x: -0.4, y: 0.2, z: 0 }, type: 'input' },
      { id: 'b', name: 'Input B', position: { x: -0.4, y: -0.2, z: 0 }, type: 'input' },
      { id: 'y', name: 'Output Y', position: { x: 0.4, y: 0, z: 0 }, type: 'output' },
    ],
    defaultProperties: { family: 'HC', propagationDelay: 12e-9 },
    size: { width: 0.8, height: 0.8, depth: 0.3 },
  },
  xor_gate: {
    type: 'xor_gate',
    name: 'XOR Gate',
    category: 'logic',
    description: 'Logical XOR (exclusive OR) gate',
    ports: [
      { id: 'a', name: 'Input A', position: { x: -0.4, y: 0.2, z: 0 }, type: 'input' },
      { id: 'b', name: 'Input B', position: { x: -0.4, y: -0.2, z: 0 }, type: 'input' },
      { id: 'y', name: 'Output Y', position: { x: 0.4, y: 0, z: 0 }, type: 'output' },
    ],
    defaultProperties: { family: 'HC', propagationDelay: 12e-9 },
    size: { width: 0.8, height: 0.8, depth: 0.3 },
  },
  switch_spdt: {
    type: 'switch_spdt',
    name: 'SPDT Switch',
    category: 'electromechanical',
    description: 'Single-pole double-throw switch',
    ports: [
      { id: 'com', name: 'Common', position: { x: 0, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'nc', name: 'Normally Closed', position: { x: -0.4, y: 0.3, z: 0 }, type: 'bidirectional' },
      { id: 'no', name: 'Normally Open', position: { x: 0.4, y: 0.3, z: 0 }, type: 'bidirectional' },
    ],
    defaultProperties: { position: 'nc' },
    size: { width: 0.8, height: 0.5, depth: 0.3 },
  },
  relay: {
    type: 'relay',
    name: 'Relay',
    category: 'electromechanical',
    description: 'Electromechanical relay switch',
    ports: [
      { id: 'coil_p', name: 'Coil +', position: { x: -0.4, y: 0.3, z: 0 }, type: 'bidirectional' },
      { id: 'coil_n', name: 'Coil -', position: { x: -0.4, y: -0.3, z: 0 }, type: 'bidirectional' },
      { id: 'com', name: 'Common', position: { x: 0.4, y: 0.2, z: 0 }, type: 'bidirectional' },
      { id: 'no', name: 'Normally Open', position: { x: 0.4, y: -0.2, z: 0 }, type: 'bidirectional' },
    ],
    defaultProperties: { coilVoltage: 5, coilResistance: 100 },
    size: { width: 1, height: 0.6, depth: 0.5 },
  },
  servo_motor: {
    type: 'servo_motor',
    name: 'Servo Motor',
    category: 'electromechanical',
    description: 'PWM-controlled servo motor',
    ports: [
      { id: 'signal', name: 'Signal (PWM)', position: { x: 0, y: 0.4, z: 0 }, type: 'input' },
      { id: 'vcc', name: 'Power (+)', position: { x: -0.3, y: -0.3, z: 0 }, type: 'power' },
      { id: 'gnd', name: 'Ground (-)', position: { x: 0.3, y: -0.3, z: 0 }, type: 'power' },
    ],
    defaultProperties: { minPulse: 1e-3, maxPulse: 2e-3, angle: 0 },
    size: { width: 0.8, height: 0.6, depth: 0.6 },
  },
  stepper_motor: {
    type: 'stepper_motor',
    name: 'Stepper Motor',
    category: 'electromechanical',
    description: 'Stepper motor with four coil wires',
    ports: [
      { id: 'a1', name: 'Coil A+', position: { x: -0.4, y: 0.2, z: 0 }, type: 'bidirectional' },
      { id: 'a2', name: 'Coil A-', position: { x: -0.4, y: -0.2, z: 0 }, type: 'bidirectional' },
      { id: 'b1', name: 'Coil B+', position: { x: 0.4, y: 0.2, z: 0 }, type: 'bidirectional' },
      { id: 'b2', name: 'Coil B-', position: { x: 0.4, y: -0.2, z: 0 }, type: 'bidirectional' },
    ],
    defaultProperties: { stepsPerRev: 200, coilResistance: 10 },
    size: { width: 1, height: 1, depth: 1 },
  },
  microphone: {
    type: 'microphone',
    name: 'Microphone',
    category: 'electromechanical',
    description: 'Electret microphone capsule',
    ports: [
      { id: 'out', name: 'Signal Out', position: { x: 0.3, y: 0, z: 0 }, type: 'output' },
      { id: 'gnd', name: 'Ground', position: { x: -0.3, y: 0, z: 0 }, type: 'power' },
    ],
    defaultProperties: { sensitivity: 0.01, biasVoltage: 3.3 },
    size: { width: 0.5, height: 0.3, depth: 0.3 },
  },
  photoresistor: {
    type: 'photoresistor',
    name: 'Photoresistor (LDR)',
    category: 'active',
    description: 'Light-dependent resistor',
    ports: [
      { id: 'p1', name: 'Pin 1', position: { x: -0.3, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'p2', name: 'Pin 2', position: { x: 0.3, y: 0, z: 0 }, type: 'bidirectional' },
    ],
    defaultProperties: { darkResistance: 1e6, lightResistance: 100 },
    size: { width: 0.5, height: 0.2, depth: 0.5 },
  },
  thermistor: {
    type: 'thermistor',
    name: 'Thermistor (NTC)',
    category: 'active',
    description: 'Temperature-dependent resistor',
    ports: [
      { id: 'p1', name: 'Pin 1', position: { x: -0.3, y: 0, z: 0 }, type: 'bidirectional' },
      { id: 'p2', name: 'Pin 2', position: { x: 0.3, y: 0, z: 0 }, type: 'bidirectional' },
    ],
    defaultProperties: { resistance25: 10000, beta: 3950 },
    size: { width: 0.4, height: 0.3, depth: 0.4 },
  },
  lcd_1602: {
    type: 'lcd_1602',
    name: 'LCD 16x2',
    category: 'display',
    description: '16x2 character LCD display',
    ports: [
      { id: 'vss', name: 'VSS (GND)', position: { x: -0.5, y: -0.5, z: 0 }, type: 'power' },
      { id: 'vdd', name: 'VDD (5V)', position: { x: -0.5, y: -0.3, z: 0 }, type: 'power' },
      { id: 'v0', name: 'V0 (Contrast)', position: { x: -0.5, y: -0.1, z: 0 }, type: 'input' },
      { id: 'rs', name: 'RS', position: { x: -0.5, y: 0.1, z: 0 }, type: 'input' },
      { id: 'rw', name: 'R/W', position: { x: -0.5, y: 0.3, z: 0 }, type: 'input' },
      { id: 'e', name: 'Enable', position: { x: -0.5, y: 0.5, z: 0 }, type: 'input' },
      { id: 'd4', name: 'D4', position: { x: 0.5, y: 0.5, z: 0 }, type: 'bidirectional' },
      { id: 'd5', name: 'D5', position: { x: 0.5, y: 0.3, z: 0 }, type: 'bidirectional' },
      { id: 'd6', name: 'D6', position: { x: 0.5, y: 0.1, z: 0 }, type: 'bidirectional' },
      { id: 'd7', name: 'D7', position: { x: 0.5, y: -0.1, z: 0 }, type: 'bidirectional' },
      { id: 'a', name: 'LED Anode', position: { x: 0.5, y: -0.3, z: 0 }, type: 'power' },
      { id: 'k', name: 'LED Cathode', position: { x: 0.5, y: -0.5, z: 0 }, type: 'power' },
    ],
    defaultProperties: { columns: 16, rows: 2 },
    size: { width: 1.5, height: 0.6, depth: 0.3 },
  },
};
